export { default as Home } from './Home'
export { default as History } from './History'
export { default as Notes } from './Notes'
export { default as Converter } from './Coverter'
export { default as Profile } from './Profile'
export { default as Signup } from './Signup'
export { default as Login } from './Login'
export { default as Authentication } from './Authentication'